import {useEffect,useRef,useState} from 'react';import {motion,animate,useMotionValue,useReducedMotion} from 'motion/react';import {Button} from '../ui/button';
export type CompanionKind='butterfly'|'frog'|'saucer';
export default function Companion({kind='butterfly',label=kind}:{kind?:CompanionKind;label?:string}){
 const lane=useRef<HTMLDivElement>(null);const x=useMotionValue(0);const reduce=useReducedMotion();const [hidden,setHidden]=useState(false);const [auto,setAuto]=useState(false);const [dragging,setDragging]=useState(false);const [inView,setInView]=useState(false);const [visible,setVisible]=useState(true);
 const stop=useRef<(()=>void)|undefined>(undefined);
 const limit=()=>Math.max(0,(lane.current?.clientWidth??56)-56);
 useEffect(()=>{const sync=()=>setAuto(document.documentElement.dataset.motion==='on');const observer=new MutationObserver(sync);observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-motion']});sync();const visibility=()=>setVisible(document.visibilityState==='visible');document.addEventListener('visibilitychange',visibility);return()=>{observer.disconnect();document.removeEventListener('visibilitychange',visibility)}},[]);
 useEffect(()=>{if(!lane.current)return;const observer=new ResizeObserver(()=>{stop.current?.();x.set(Math.min(limit(),Math.max(0,x.get())))});observer.observe(lane.current);const intersection=new IntersectionObserver(entries=>setInView(entries[0]?.isIntersecting??false));intersection.observe(lane.current);return()=>{observer.disconnect();intersection.disconnect()}},[x]);
 useEffect(()=>{stop.current?.();if(!auto||reduce||dragging||hidden||!inView||!visible)return;const stroll=()=>{const next=Math.random()*limit();const animation=animate(x,next,{duration:7,ease:'easeInOut'});stop.current=()=>animation.stop()};stroll();const timer=window.setInterval(stroll,9000);return()=>{clearInterval(timer);stop.current?.()}},[auto,reduce,dragging,hidden,inView,visible,x]);
 function move(direction:number){stop.current?.();setAuto(false);x.set(Math.max(0,Math.min(limit(),x.get()+direction*40)))}
 return <section className="companion-section" aria-label={`${label} companion`}><div className="companion-lane" ref={lane}>{!hidden&&<motion.button type="button" className="companion" drag="x" dragConstraints={lane} dragElastic={0} dragMomentum={false} style={{x,touchAction:'pan-y'}} onDragStart={()=>{stop.current?.();setDragging(true)}} onDragEnd={()=>{x.set(Math.max(0,Math.min(limit(),x.get())));setDragging(false);setAuto(false)}} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();move(e.key==='ArrowLeft'?-1:1)}if(e.key==='Home'){e.preventDefault();stop.current?.();setAuto(false);x.set(0)}if(e.key==='End'){e.preventDefault();stop.current?.();setAuto(false);x.set(limit())}}} aria-label={`${label}: drag along the lane or use left and right arrow keys`}><img src={`/characters/${kind}.svg`} alt="" width="48" height="48" draggable={false}/></motion.button>}</div><div className="companion-caption"><span>{label} · Drag or use arrow keys</span><Button variant="outline" onClick={()=>setHidden(!hidden)}>{hidden?'Show companion':'Hide companion'}</Button></div></section>
}
